ERROR_UNKNOWN_COMMAND = 0x40000001
ERROR_COMMAND_NOT_IMPLEMENTED = 0x40000002
ERROR_INVALID_REQUEST = 0x40000003
ERROR_THREAD_CREATE_FAILED = 0x40000004
ERROR_NETWORK_INIT_FAILED = 0x40000005
ERROR_SEND_FAILED = 0x40000006
ERROR_RECV_FAILED = 0x40000007
ERROR_MEMORY_ALLOCATION_FAILED = 0x40000008
ERROR_OPEN_PROCESS_TOKEN_FAILED = 0x40000009
ERROR_OPEN_THREAD_TOKEN_FAILED = 0x4000000A
ERROR_QUERY_TOKEN_USER_FAILED = 0x4000000B
ERROR_QUERY_TOKEN_ELEVATION_FAILED = 0x4000000C
ERROR_LOOKUP_ACCOUNT_SID_FAILED = 0x4000000D
ERROR_CONVERT_SID_TO_STRING_FAILED = 0x4000000E
ERROR_FORMAT_ACCOUNT_NAME_FAILED = 0x4000000F

ERROR_MESSAGES = {
    ERROR_UNKNOWN_COMMAND: 'Unknown command',
    ERROR_COMMAND_NOT_IMPLEMENTED: 'Command not implemented',
    ERROR_INVALID_REQUEST: 'Invalid request',
    ERROR_THREAD_CREATE_FAILED: 'Failed to create worker thread',
    ERROR_NETWORK_INIT_FAILED: 'Network initialization failed',
    ERROR_SEND_FAILED: 'Failed to send response',
    ERROR_RECV_FAILED: 'Failed to receive request',
    ERROR_MEMORY_ALLOCATION_FAILED: 'Memory allocation failed',
    ERROR_OPEN_PROCESS_TOKEN_FAILED: 'Failed to open process token',
    ERROR_OPEN_THREAD_TOKEN_FAILED: 'Failed to open thread token',
    ERROR_QUERY_TOKEN_USER_FAILED: 'Failed to query token user information',
    ERROR_QUERY_TOKEN_ELEVATION_FAILED: 'Failed to query token elevation information',
    ERROR_LOOKUP_ACCOUNT_SID_FAILED: 'Failed to resolve SID to account name',
    ERROR_CONVERT_SID_TO_STRING_FAILED: 'Failed to convert SID to string',
    ERROR_FORMAT_ACCOUNT_NAME_FAILED: 'Failed to format account name',
}
